# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='example',
  syntax='proto3',
  serialized_pb=_b('\n\ndata.proto\x12\x07\x65xample\"\x1b\n\x07\x43MDInfo\x12\x10\n\x08\x63md_type\x18\x01 \x01(\x05\"n\n\tShelfInfo\x12\x13\n\x0b\x64oor_status\x18\x01 \x01(\x05\x12\x14\n\x0clight_status\x18\x02 \x01(\x05\x12\x15\n\rcamera_status\x18\x03 \x01(\x05\x12\x10\n\x08shelf_id\x18\x04 \x01(\x05\x12\r\n\x05image\x18\x05 \x01(\x0c\x32@\n\nFormatData\x12\x32\n\x08\x44oFormat\x12\x12.example.ShelfInfo\x1a\x10.example.CMDInfo\"\x00\x62\x06proto3')
)




_CMDINFO = _descriptor.Descriptor(
  name='CMDInfo',
  full_name='example.CMDInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_type', full_name='example.CMDInfo.cmd_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=50,
)


_SHELFINFO = _descriptor.Descriptor(
  name='ShelfInfo',
  full_name='example.ShelfInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='door_status', full_name='example.ShelfInfo.door_status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='light_status', full_name='example.ShelfInfo.light_status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_status', full_name='example.ShelfInfo.camera_status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shelf_id', full_name='example.ShelfInfo.shelf_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='example.ShelfInfo.image', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['CMDInfo'] = _CMDINFO
DESCRIPTOR.message_types_by_name['ShelfInfo'] = _SHELFINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CMDInfo = _reflection.GeneratedProtocolMessageType('CMDInfo', (_message.Message,), dict(
  DESCRIPTOR = _CMDINFO,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.CMDInfo)
  ))
_sym_db.RegisterMessage(CMDInfo)

ShelfInfo = _reflection.GeneratedProtocolMessageType('ShelfInfo', (_message.Message,), dict(
  DESCRIPTOR = _SHELFINFO,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.ShelfInfo)
  ))
_sym_db.RegisterMessage(ShelfInfo)



_FORMATDATA = _descriptor.ServiceDescriptor(
  name='FormatData',
  full_name='example.FormatData',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=164,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoFormat',
    full_name='example.FormatData.DoFormat',
    index=0,
    containing_service=None,
    input_type=_SHELFINFO,
    output_type=_CMDINFO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FORMATDATA)

DESCRIPTOR.services_by_name['FormatData'] = _FORMATDATA

# @@protoc_insertion_point(module_scope)
